
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBib8wcw3EJwlliWA5Ou0LhnX-3zMVu9aM',
    appId: '1:341335807389:web:8e189605d7a71df38c0b74',
    messagingSenderId: '341335807389',
    projectId: 'bus-management-app-6517d',
    authDomain: 'bus-management-app-6517d.firebaseapp.com',
    storageBucket: 'bus-management-app-6517d.firebasestorage.app',
    measurementId: 'G-H1GYE44CCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV76LovvWhg22dBPnNyh7G0UKWGaUFqu4',
    appId: '1:341335807389:android:60ef22eb420d59dd8c0b74',
    messagingSenderId: '341335807389',
    projectId: 'bus-management-app-6517d',
    storageBucket: 'bus-management-app-6517d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA65F_ACFX34qoQaeKT3ZP6sHEtk8pNIAo',
    appId: '1:341335807389:ios:e2b325c10f249a538c0b74',
    messagingSenderId: '341335807389',
    projectId: 'bus-management-app-6517d',
    storageBucket: 'bus-management-app-6517d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA65F_ACFX34qoQaeKT3ZP6sHEtk8pNIAo',
    appId: '1:341335807389:ios:e2b325c10f249a538c0b74',
    messagingSenderId: '341335807389',
    projectId: 'bus-management-app-6517d',
    storageBucket: 'bus-management-app-6517d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBib8wcw3EJwlliWA5Ou0LhnX-3zMVu9aM',
    appId: '1:341335807389:web:a4435a36a45ec6ba8c0b74',
    messagingSenderId: '341335807389',
    projectId: 'bus-management-app-6517d',
    authDomain: 'bus-management-app-6517d.firebaseapp.com',
    storageBucket: 'bus-management-app-6517d.firebasestorage.app',
    measurementId: 'G-QK072YQ1NM',
  );
}
